# setup
setup: clustering

# Loss
criterion: clustering
criterion_kwargs:
   entropy_weight: 5.0

# Weight update
update_cluster_head_only: True
num_heads: 1

# Model
backbone: ViT-B/32

# Dataset
train_db_name: imagenet_dog
val_db_name: imagenet_dog
num_classes: 15
num_neighbors: 20

# Transformations
augmentation_strategy: simclr 
augmentation_kwargs:
   random_resized_crop:
      size: 224
      scale: [0.2, 1.0]
   color_jitter_random_apply:
      p: 0.8
   color_jitter:
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0.1
   random_grayscale: 
      p: 0.2
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

transformation_kwargs:
   crop_size: 224
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

# Hyperparameters
optimizer_image:
   optimizer: adam
   optimizer_kwargs:
      lr: 0.0001
      weight_decay: 0.009
   scheduler: constant

lr_decay_rate: 0.001
epochs: 100
batch_size: 128 #128
num_workers: 8 #8